apiVersion: apps/v1
kind: Deployment
metadata:
  name: CCE-SSR-Example-App
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: CCE-SSR-Example-App
  template:
    metadata:
      labels:
        app: CCE-SSR-Example-App
    spec:
      containers:
        - image: 097916242697.dkr.ecr.us-east-2.amazonaws.com/eks-beta-208024-ssr_example_app:bd9bd143386fc00121a65ac1a3768299e892a4b5
          name: eks-beta-208024-ssr_example_app
          ports:
            - containerPort: 80
